version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: book-management-system-api
    command: uvicorn app.main:app --workers 2 --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - ./app/:/usr/src/app/
    working_dir: /usr/src/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M